### ISSUE TITLE
Sensor Error 확인 (SCC 추가)

### ISSUE THREAD

**Issue by hanbro-inha** [kka-na/aeye#12]

**Comment by kyeongjunJang** [comment]
https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/error/error_check.py#L34
https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/error/error_check.py#L55
https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/error/error_check.py#L80-L81
https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/error/error_check.py#L131-L134

https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/control/can_bridge.py#L82
https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/control/can_bridge.py#L90-L91
https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/control/can_bridge.py#L139
https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/control/can_bridge.py#L184-L187
https://github.com/kka-na/aeye/blob/c5882a6999cba2e83b9aa1b67018c56a757ec16d/control/can_bridge.py#L192
