### ISSUE TITLE
Changing Mode Bug

### ISSUE THREAD

**Issue by kka-na** [kka-na/aeye#16]
https://github.com/kka-na/aeye/blob/311cedc564aa6e38a8fe95a78c48aff0d40a2c56/control/can_bridge.py#L208-L209

이거를 카운트를 걸어서 10 이전 값이랑 다르고, 10 셌을때 0으로 초기화 해주면 될 것 같아유 

`
self.can_cnt = 0
...
if self.can_cnt > 10 and 1 in self.switch : 
    self.switch = [0, 0, 0]
`

**Comment by kyeongjunJang** [comment]
https://github.com/kka-na/aeye/blob/20a93af8ada7a4687f5ece5979a0f54bd43dab31/control/can_bridge.py#L207-L216

**Comment by kyeongjunJang** [comment]
https://github.com/kka-na/aeye/blob/2477cbc95223dcb3db3d83aeecc72efc16e7a2a7/control/can_bridge.py#L286-L292
