### ISSUE TITLE
AEB

### ISSUE THREAD

**Issue by kka-na** [kka-na/aeye#18]
- [x] CAN AEB Message Recording & Analyzing
- [x] Implement AEB TOR Request Process

**Comment by kka-na** [comment]
- [x] Analyzing Openpilot UI "BRAKE!" Warning

https://github.com/commaai/openpilot/blob/0fce5d90459b77bf2cfa70f55f322f0e1fb8d01c/selfdrive/controls/lib/events.py#L397-L412

@hanbro-inha 🐟

**Comment by hanbro-inha** [comment]
> * [x]  Analyzing Openpilot UI "BRAKE!" Warning
> 
> https://github.com/commaai/openpilot/blob/0fce5d90459b77bf2cfa70f55f322f0e1fb8d01c/selfdrive/controls/lib/events.py#L397-L412
> 
> @hanbro-inha 🐟

@kka-na🌼 역쉬이 가나아~~

**Comment by kka-na** [comment]
hyundai 에서는 FCA11의 FCA_CmdAct 이나 SCC12의 AEB_CmdAct 를 봐야하나 봐용

https://github.com/commaai/openpilot/blob/4c7cb028b1ae05ea20e5fc7ca3a2bda96fcdf9f4/selfdrive/car/hyundai/carstate.py#L109-L115

**Comment by kka-na** [comment]
> > * [x]   Analyzing Openpilot UI "BRAKE!" Warning
> > 
> > https://github.com/commaai/openpilot/blob/0fce5d90459b77bf2cfa70f55f322f0e1fb8d01c/selfdrive/controls/lib/events.py#L397-L412
> > @hanbro-inha 🐟
> 
> @kka-na🌼 역쉬이 가나아~~

hyundai 에서는 FCA11의 FCA_CmdAct 이나 SCC12의 AEB_CmdAct 를 봐야하나 봐용

https://github.com/commaai/openpilot/blob/4c7cb028b1ae05ea20e5fc7ca3a2bda96fcdf9f4/selfdrive/car/hyundai/carstate.py#L109-L115

**Comment by kka-na** [comment]
https://github.com/kka-na/aeye/blob/b971a2627aa0f84945695882a571aef70bb38d52/control/can_bridge.py#L132-L134

https://github.com/kka-na/aeye/blob/b971a2627aa0f84945695882a571aef70bb38d52/control/can_bridge.py#L248-L255

**Comment by kka-na** [comment]
ADD Event 

https://github.com/commaai/openpilot/blob/7c826b4fa1ff5d4a22da4a9643ecef803c0b7536/selfdrive/controls/controlsd.py#L354-L359
