### ISSUE TITLE
Functionality Update

### ISSUE THREAD

**Issue by hanbro-inha** [kka-na/aeye#2]
### Functionality Update for Demo ready version 
- [x] #3
- [x] #4
- [x] #8
- [x] #9
- [x] #7
- [x] #11
- [x] #12
- [x] #10
- [x] #17
- [x] #18
- [x] #19
- [x] #22
- [x] #21
- [x] #23

**Comment by kka-na** [comment]
- [ ] BSD 상황에서의 무한 차선 변경 Bug Fix 
> 차선 변경 시 BSD 상황이면 변경 못하고, BSD 해제 후 차선 변경 함. 근데 Left Blinker가 계속 켜져있으면 한번 더 넘어감 

https://github.com/kka-na/aeye/blob/4a82b39bad16bd36b225b557ad7acdef3aaf01a9/control/openpilot/lateral_planner.py#L191-L194

Timer가 10으로 Set되는 부분? 

https://github.com/kka-na/aeye/blob/4a82b39bad16bd36b225b557ad7acdef3aaf01a9/control/openpilot/lateral_planner.py#L208-L214

BSD 상황에서는 208 if 문에 걸려서 LaneChangeState 가 계속 PreLaneChange State 이고, Timer도 계속 0으로 초기화 되서 무한 차선변경 걸리는 거 같은데 print하면서 분석해야 할거같아염 

https://github.com/kka-na/aeye/blob/4a82b39bad16bd36b225b557ad7acdef3aaf01a9/control/openpilot/lateral_planner.py#L228-L236

Timer Addition 부분

**Comment by kka-na** [comment]
- [x] lane_check Class 화 시키기 
> while문 keyboard interrupt 추가~~~ 

https://github.com/kka-na/aeye/blob/4a82b39bad16bd36b225b557ad7acdef3aaf01a9/control/openpilot/lane_check.py#L40

**Comment by kka-na** [comment]
> 

https://github.com/kka-na/aeye/blob/9d6ea859f33f3ed50519ee293652bc8e834e3336/control/openpilot/lane_check.py#L10

**Comment by kka-na** [comment]
> * [x]  lane_check Class 화 시키기
> 
> > while문 keyboard interrupt 추가~~~
> 
> https://github.com/kka-na/aeye/blob/4a82b39bad16bd36b225b557ad7acdef3aaf01a9/control/openpilot/lane_check.py#L40

https://github.com/kka-na/aeye/blob/9d6ea859f33f3ed50519ee293652bc8e834e3336/control/openpilot/lane_check.py#L10

**Comment by kka-na** [comment]
화이팅 🔥❤️🔥❤️🔥❤️🔥❤️
