### ISSUE TITLE
Functionality Update

### ISSUE THREAD

**Issue by kka-na** [kka-na/aeye#24]
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32

**Comment by kka-na** [comment]
Add Count for Keep Autopilot mode ( 2 seconds )

https://github.com/kka-na/aeye/blob/25a31e677aaa93f4d93bf47a57ab4a257dac7cc0/error/mode_check.py#L53-L60

**Comment by hanbro-inha** [comment]
END OF PROJECT 
🙋‍♂️🙋‍♀️🙋
