### ISSUE TITLE
Clean Repository

### ISSUE THREAD

**Issue by hanbro-inha** [kka-na/aeye#5]
- [x] #13
- [x] #14
- [x] 블랙박스
- [x] 스피커
- [x] 선 정리
- [x] NUC 전원 선
- [x] TDS-1 CAN 선 
- [x] #6

**Comment by hanbro-inha** [comment]
레이더 코드 추가하고 기존에 필요없는 코드는 지워버리자

**Comment by kyeongjunJang** [comment]
![image](https://user-images.githubusercontent.com/63050716/173337530-5d6f5095-376a-4a71-9ffd-4c5ccef3f3ad.png)

**Comment by hanbro-inha** [comment]
![rosgraph](https://user-images.githubusercontent.com/61651470/173355236-32c0bdac-9787-49c5-a6b2-bc1338cfd740.png)

**Comment by hanbro-inha** [comment]
![rosgraph](https://user-images.githubusercontent.com/61651470/173356197-10e39eae-f1dc-4d87-ab4d-5a35c8ef74be.png)
